# Generated by Django 4.2.23 on 2025-10-05 04:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('Credit Card', 'Thẻ tín dụng'), ('PayPal', 'PayPal'), ('Bank Transfer', 'Chuyển khoản ngân hàng')], max_length=20)),
                ('transaction_code', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('Pending', 'Chờ xử lý'), ('Completed', 'Hoàn thành'), ('Failed', 'Thất bại')], default='Pending', max_length=10)),
                ('payment_time', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
                'ordering': ['-payment_time'],
            },
        ),
    ]
