create table django_migrations
(
    id      bigint generated by default as identity,
    app     varchar(255)             not null,
    name    varchar(255)             not null,
    applied timestamp with time zone not null
);

alter table django_migrations
    owner to postgres;

alter table django_migrations
    add primary key (id);

create table users
(
    id           bigint generated by default as identity,
    username     varchar(300)             not null,
    email        varchar(254)             not null,
    first_name   varchar(30)              not null,
    last_name    varchar(30)              not null,
    password     varchar(255)             not null,
    role         varchar(20)              not null,
    permissions  jsonb                    not null,
    is_active    boolean                  not null,
    is_verified  boolean                  not null,
    is_staff     boolean                  not null,
    is_superuser boolean                  not null,
    date_joined  timestamp with time zone not null,
    last_login   timestamp with time zone
);

alter table users
    owner to postgres;

create index users_username_e8658fc8_like
    on users (username varchar_pattern_ops);

create index users_email_0ea73cca_like
    on users (email varchar_pattern_ops);

alter table users
    add primary key (id);

alter table users
    add unique (username);

alter table users
    add unique (email);

create table user_sessions
(
    id            bigint generated by default as identity,
    session_key   varchar(255)             not null,
    created_at    timestamp with time zone not null,
    last_activity timestamp with time zone not null,
    ip_address    inet                     not null,
    user_agent    varchar(255)             not null,
    is_active     boolean                  not null,
    user_id       bigint                   not null
);

alter table user_sessions
    owner to postgres;

create index user_sessions_session_key_5c5616a8_like
    on user_sessions (session_key varchar_pattern_ops);

create index user_sessions_user_id_43ce9642
    on user_sessions (user_id);

alter table user_sessions
    add primary key (id);

alter table user_sessions
    add unique (session_key);

alter table user_sessions
    add constraint user_sessions_user_id_43ce9642_fk_users_id
        foreign key (user_id) references users
            deferrable initially deferred;

create table django_content_type
(
    id        integer generated by default as identity,
    app_label varchar(100) not null,
    model     varchar(100) not null
);

alter table django_content_type
    owner to postgres;

alter table django_content_type
    add primary key (id);

alter table django_content_type
    add constraint django_content_type_app_label_model_76bd3d3b_uniq
        unique (app_label, model);

create table django_admin_log
(
    id              integer generated by default as identity,
    action_time     timestamp with time zone not null,
    object_id       text,
    object_repr     varchar(200)             not null,
    action_flag     smallint                 not null,
    change_message  text                     not null,
    content_type_id integer,
    user_id         bigint                   not null
);

alter table django_admin_log
    owner to postgres;

create index django_admin_log_content_type_id_c4bce8eb
    on django_admin_log (content_type_id);

create index django_admin_log_user_id_c564eba6
    on django_admin_log (user_id);

alter table django_admin_log
    add primary key (id);

alter table django_admin_log
    add constraint django_admin_log_content_type_id_c4bce8eb_fk_django_co
        foreign key (content_type_id) references django_content_type
            deferrable initially deferred;

alter table django_admin_log
    add constraint django_admin_log_user_id_c564eba6_fk_users_id
        foreign key (user_id) references users
            deferrable initially deferred;

alter table django_admin_log
    add constraint django_admin_log_action_flag_check
        check (action_flag >= 0);

create table auth_permission
(
    id              integer generated by default as identity,
    name            varchar(255) not null,
    content_type_id integer      not null,
    codename        varchar(100) not null
);

alter table auth_permission
    owner to postgres;

create index auth_permission_content_type_id_2f476e4b
    on auth_permission (content_type_id);

alter table auth_permission
    add primary key (id);

alter table auth_permission
    add constraint auth_permission_content_type_id_codename_01ab375a_uniq
        unique (content_type_id, codename);

alter table auth_permission
    add constraint auth_permission_content_type_id_2f476e4b_fk_django_co
        foreign key (content_type_id) references django_content_type
            deferrable initially deferred;

create table auth_group
(
    id   integer generated by default as identity,
    name varchar(150) not null
);

alter table auth_group
    owner to postgres;

create index auth_group_name_a6ea08ec_like
    on auth_group (name varchar_pattern_ops);

alter table auth_group
    add primary key (id);

alter table auth_group
    add unique (name);

create table auth_group_permissions
(
    id            bigint generated by default as identity,
    group_id      integer not null,
    permission_id integer not null
);

alter table auth_group_permissions
    owner to postgres;

create index auth_group_permissions_group_id_b120cbf9
    on auth_group_permissions (group_id);

create index auth_group_permissions_permission_id_84c5c92e
    on auth_group_permissions (permission_id);

alter table auth_group_permissions
    add primary key (id);

alter table auth_group_permissions
    add constraint auth_group_permissions_group_id_permission_id_0cd325b0_uniq
        unique (group_id, permission_id);

alter table auth_group_permissions
    add constraint auth_group_permissions_group_id_b120cbf9_fk_auth_group_id
        foreign key (group_id) references auth_group
            deferrable initially deferred;

alter table auth_group_permissions
    add constraint auth_group_permissio_permission_id_84c5c92e_fk_auth_perm
        foreign key (permission_id) references auth_permission
            deferrable initially deferred;

create table buses
(
    id               bigint generated by default as identity,
    license_plate    varchar(30)  not null,
    model            varchar(100) not null,
    total_seats      integer      not null,
    manufacture_year integer      not null
);

alter table buses
    owner to postgres;

create index buses_license_plate_b7203ba4_like
    on buses (license_plate varchar_pattern_ops);

alter table buses
    add primary key (id);

alter table buses
    add unique (license_plate);

alter table buses
    add constraint buses_total_seats_check
        check (total_seats >= 0);

alter table buses
    add constraint buses_manufacture_year_check
        check (manufacture_year >= 0);

create table locations
(
    id   bigint generated by default as identity,
    name varchar(255) not null,
    city varchar(100) not null
);

alter table locations
    owner to postgres;

alter table locations
    add primary key (id);

create table routes
(
    id                bigint generated by default as identity,
    distance_km       double precision not null,
    end_location_id   bigint           not null,
    start_location_id bigint           not null
);

alter table routes
    owner to postgres;

create index routes_end_location_id_887fe0af
    on routes (end_location_id);

create index routes_start_location_id_355e3cb1
    on routes (start_location_id);

alter table routes
    add primary key (id);

alter table routes
    add constraint routes_start_location_id_end_location_id_47173a8c_uniq
        unique (start_location_id, end_location_id);

alter table routes
    add constraint routes_end_location_id_887fe0af_fk_locations_id
        foreign key (end_location_id) references locations
            deferrable initially deferred;

alter table routes
    add constraint routes_start_location_id_355e3cb1_fk_locations_id
        foreign key (start_location_id) references locations
            deferrable initially deferred;

create table trips
(
    id             bigint generated by default as identity,
    departure_time timestamp with time zone not null,
    arrival_time   timestamp with time zone not null,
    price_per_seat numeric(10, 2)           not null,
    bus_id         bigint                   not null,
    route_id       bigint                   not null
);

alter table trips
    owner to postgres;

create index trips_bus_id_0f292d2d
    on trips (bus_id);

create index trips_route_id_715fed1b
    on trips (route_id);

alter table trips
    add primary key (id);

alter table trips
    add constraint trips_bus_id_0f292d2d_fk_buses_id
        foreign key (bus_id) references buses
            deferrable initially deferred;

alter table trips
    add constraint trips_route_id_715fed1b_fk_routes_id
        foreign key (route_id) references routes
            deferrable initially deferred;

create table seats
(
    id           bigint generated by default as identity,
    seat_number  varchar(10) not null,
    is_available boolean     not null,
    bus_id       bigint      not null
);

alter table seats
    owner to postgres;

create index seats_bus_id_6ef4699d
    on seats (bus_id);

alter table seats
    add primary key (id);

alter table seats
    add constraint seats_bus_id_seat_number_5458c34b_uniq
        unique (bus_id, seat_number);

alter table seats
    add constraint seats_bus_id_6ef4699d_fk_buses_id
        foreign key (bus_id) references buses
            deferrable initially deferred;

create table bookings
(
    id              bigint generated by default as identity,
    number_of_seats integer                  not null,
    total_amount    numeric(10, 2)           not null,
    booking_time    timestamp with time zone not null,
    status          varchar(10)              not null,
    trip_id         bigint                   not null,
    user_id         bigint
);

comment on column bookings.user_id is 'User ID - NULL for guest bookings';

alter table bookings
    owner to postgres;

create index bookings_trip_id_89bc46e9
    on bookings (trip_id);

create index bookings_user_id_6e734b08
    on bookings (user_id);

alter table bookings
    add primary key (id);

alter table bookings
    add constraint bookings_trip_id_89bc46e9_fk_trips_id
        foreign key (trip_id) references trips
            deferrable initially deferred;

alter table bookings
    add constraint bookings_user_id_6e734b08_fk_users_id
        foreign key (user_id) references users
            deferrable initially deferred;

alter table bookings
    add constraint bookings_number_of_seats_check
        check (number_of_seats >= 0);

create table tickets
(
    id             bigint generated by default as identity,
    price          numeric(10, 2) not null,
    passenger_name varchar(100)   not null,
    booking_id     bigint         not null,
    seat_id        bigint         not null,
    trip_id        bigint         not null
);

alter table tickets
    owner to postgres;

create index tickets_booking_id_d9ce02d0
    on tickets (booking_id);

create index tickets_seat_id_e8dc5a36
    on tickets (seat_id);

create index tickets_trip_id_b68c10e7
    on tickets (trip_id);

alter table tickets
    add primary key (id);

alter table tickets
    add constraint tickets_trip_id_seat_id_a241093c_uniq
        unique (trip_id, seat_id);

alter table tickets
    add constraint tickets_booking_id_d9ce02d0_fk_bookings_id
        foreign key (booking_id) references bookings
            deferrable initially deferred;

alter table tickets
    add constraint tickets_seat_id_e8dc5a36_fk_seats_id
        foreign key (seat_id) references seats
            deferrable initially deferred;

alter table tickets
    add constraint tickets_trip_id_b68c10e7_fk_trips_id
        foreign key (trip_id) references trips
            deferrable initially deferred;

create table django_session
(
    session_key  varchar(40)              not null,
    session_data text                     not null,
    expire_date  timestamp with time zone not null
);

alter table django_session
    owner to postgres;

create index django_session_session_key_c0390e0f_like
    on django_session (session_key varchar_pattern_ops);

create index django_session_expire_date_a5c62663
    on django_session (expire_date);

alter table django_session
    add primary key (session_key);

create table social_auth_association
(
    id         bigint generated by default as identity,
    server_url varchar(255) not null,
    handle     varchar(255) not null,
    secret     varchar(255) not null,
    issued     integer      not null,
    lifetime   integer      not null,
    assoc_type varchar(64)  not null
);

alter table social_auth_association
    owner to postgres;

alter table social_auth_association
    add primary key (id);

alter table social_auth_association
    add constraint social_auth_association_server_url_handle_078befa2_uniq
        unique (server_url, handle);

create table social_auth_code
(
    id        bigint generated by default as identity,
    email     varchar(254)             not null,
    code      varchar(32)              not null,
    verified  boolean                  not null,
    timestamp timestamp with time zone not null
);

alter table social_auth_code
    owner to postgres;

create index social_auth_code_code_a2393167
    on social_auth_code (code);

create index social_auth_code_code_a2393167_like
    on social_auth_code (code varchar_pattern_ops);

create index social_auth_code_timestamp_176b341f
    on social_auth_code (timestamp);

alter table social_auth_code
    add primary key (id);

alter table social_auth_code
    add constraint social_auth_code_email_code_801b2d02_uniq
        unique (email, code);

create table social_auth_nonce
(
    id         bigint generated by default as identity,
    server_url varchar(255) not null,
    timestamp  integer      not null,
    salt       varchar(65)  not null
);

alter table social_auth_nonce
    owner to postgres;

alter table social_auth_nonce
    add primary key (id);

alter table social_auth_nonce
    add constraint social_auth_nonce_server_url_timestamp_salt_f6284463_uniq
        unique (server_url, timestamp, salt);

create table social_auth_usersocialauth
(
    id         bigint generated by default as identity,
    provider   varchar(32)              not null,
    uid        varchar(255)             not null,
    user_id    bigint                   not null,
    created    timestamp with time zone not null,
    modified   timestamp with time zone not null,
    extra_data jsonb                    not null
);

alter table social_auth_usersocialauth
    owner to postgres;

create index social_auth_usersocialauth_user_id_17d28448
    on social_auth_usersocialauth (user_id);

create index social_auth_usersocialauth_uid_796e51dc
    on social_auth_usersocialauth (uid);

create index social_auth_usersocialauth_uid_796e51dc_like
    on social_auth_usersocialauth (uid varchar_pattern_ops);

alter table social_auth_usersocialauth
    add primary key (id);

alter table social_auth_usersocialauth
    add constraint social_auth_usersocialauth_provider_uid_e6b5e668_uniq
        unique (provider, uid);

alter table social_auth_usersocialauth
    add constraint social_auth_usersocialauth_user_id_17d28448_fk_users_id
        foreign key (user_id) references users
            deferrable initially deferred;

create table social_auth_partial
(
    id        bigint generated by default as identity,
    token     varchar(32)              not null,
    next_step smallint                 not null,
    backend   varchar(32)              not null,
    timestamp timestamp with time zone not null,
    data      jsonb                    not null
);

alter table social_auth_partial
    owner to postgres;

create index social_auth_partial_token_3017fea3
    on social_auth_partial (token);

create index social_auth_partial_token_3017fea3_like
    on social_auth_partial (token varchar_pattern_ops);

create index social_auth_partial_timestamp_50f2119f
    on social_auth_partial (timestamp);

alter table social_auth_partial
    add primary key (id);

alter table social_auth_partial
    add constraint social_auth_partial_next_step_check
        check (next_step >= 0);

create table payments
(
    id               uuid default gen_random_uuid() not null,
    booking_id       bigint                         not null,
    amount           numeric(10, 2)                 not null,
    payment_method   varchar(20)                    not null,
    status           varchar(10)                    not null,
    payment_time     timestamp with time zone       not null,
    transaction_code varchar(255)                   not null
);

alter table payments
    owner to postgres;

create index idx_payments_booking_id
    on payments (booking_id);

create index idx_payments_status
    on payments (status);

alter table payments
    add primary key (id);

alter table payments
    add foreign key (booking_id) references bookings
        on delete cascade;


